function subjects = subject_info

%% Behavioural-fMRI subjects

subjects(1) = struct('id', '149', ...
    'session_folder_name',{{'2016_12_14','2016_12_16','2016_12_17','2016_12_20','2017_02_02', ...
                            '2017_02_07','2017_02_08','2017_02_09','2017_02_15','2017_03_21','2017_04_04',...
                            '2017_04_13'}}, ...
    'psychophysics', struct('baseline', struct('session', 5, 'runid', {{2}}), ...
                            'test', struct('session', 5, 'runid', {{3:5}}, 'nblocks', {{[1 2 2]}}), ...
                            'VE', struct('session', 5, 'runid', {{6:8}}), ...
                            'adapt', struct('session', 5, 'runid', {{9}}), ...
                            'pretest', struct('session', 6:9, 'runid', {{1 1 1 1}}, ...
                                              'match', {{'R' 'L' 'L' 'R'}}), ...
                            'posttest', struct('session', 6:9,...
                                               'radapt', struct('session', [6 9], ...
                                                                'runid', {{2:3 2:3}}, ...
                                                                'nblocks', {{[5 5] [5 5]}}), ...
                                               'ladapt', struct('session', 7:8, ...
                                                                'runid', {{2:3 2:3}}, ...
                                                                'nblocks', {{[5 5] [5 5]}}))), ...
    'anat', struct('session', 1), ...
    'fMRI', struct('session', 1:4, ...
                   'pretest', struct('session', 1:4, 'runid', {{3:7 [5:7 9:10] [4:6 10:11] 4:8}}, ...
                                     'hand', {{['L' 'R' 'L' 'R' 'L'], ['R' 'L' 'R' 'L' 'R'], ...
                                               ['L' 'R' 'L' 'R' 'L'], ['R' 'L' 'R' 'L' 'R']}}, ...
                                     'match', {{'R' 'L' 'L' 'R'}}), ...  
                   'posttest', struct('session', 1:4, ...
                                      'radapt', struct('session', [1 4], 'runid', {{10:14 10:13}}, ...
                                                       'hand', {{['L' 'R' 'R' 'L' 'R'], ...
                                                                 ['R' 'L' 'R' 'L']}}, ...
                                                       'min3', {{[1 0 0 0 1 0 0 0] [1 0 0 0 1 0 0 0]}}, ...
                                                       'mergerun', {{[3] []}}), ...
                                      'ladapt', struct('session', [2 3], 'runid', {{12:16 13:17}}, ...
                                                       'hand', {{['R' 'R' 'L' 'R' 'L'], ...
                                                                 ['L' 'L' 'R' 'L' 'R']}}, ...
                                                       'min3', {{[1 1 0 0 1 0 0 0] [1 1 0 0 1 0 0 0]}}, ...
                                                       'mergerun', {{[2] [2]}}))), ...
     'EEG', struct('session',[10,12], ...
                   'pretest',struct('session',[10,12],'runid',{{4:13,2:11}},'match',{{'R','L'}}), ...
                   'posttest',struct('session',[10,12], ...
                                     'radapt',struct('session',10, ...
                                                     'runid',{{14:21}}, ...
                                                     'min3',{{ones(1,16),}}), ...
                                     'ladapt',struct('session',12, ...
                                                     'runid',{{12:19}}, ...
                                                     'min3',{{ones(1,16)}})), ...
                   'filespec',struct('session',{10,12}, ...
                                     'file',{struct('name',{'149_session10_1','149_session10_2', ...
                                                            '149_session10_3','149_session10_4'}, ...
                                                  'session',{10,10,10,10}, ...
                                                  'nRunsInFile',{5,5,4,4}, ...
                                                  'nBlocksInFile',{10,10,16,16},...
                                                  'runid',{4:8,9:13,14:17,18:21},...
                                                  'hand',{{'R','L','R','L','R'},...
                                                          {'L','R','L','R','L'},...
                                                          {'R','L','R','L'},...
                                                          {'R','L','R','L'}},...
                                                  'runsToExclude',{NaN,NaN,NaN,NaN}, ...
                                                  'blocksToExclude',{NaN,NaN,NaN,NaN},...
                                                  'cutoff_zval',{4,4,4,4}),...
                                            struct('name',{'149_session12_1','149_session12_2', ...
                                                            '149_session12_3','149_session12_4',...
                                                            '149_session12_5'}, ...
                                                  'session',{12,12,12,12,12}, ...
                                                  'nRunsInFile',{5,5,4,3,1}, ...
                                                  'nBlocksInFile',{10,10,16,12,4},...
                                                  'runid',{2:6,7:11,12:15,16:18,19},...
                                                  'hand',{{'L','R','L','R','L'},...
                                                          {'R','L','R','L','R'},...
                                                          {'L','R','L','R'},...
                                                          {'L','R','L'},{'R'}},...
                                                  'runsToExclude',{NaN,NaN,NaN,NaN,NaN}, ...
                                                  'blocksToExclude',{NaN,NaN,NaN,NaN,NaN},...
                                                  'cutoff_zval',{4,4,4,4,4})})));

subjects(2) = struct('id', '336', ...
    'session_folder_name',{{'2016_11_17','2016_11_22','2016_11_24','2016_11_28','2016_11_30', ...
                            '2017_01_14','2017_01_15','2017_01_21','2017_01_22','2017_05_07',...
                            '2017_05_08','2017_05_09','2017_05_10'}}, ...
    'psychophysics', struct('baseline', struct('session', 1, 'runid', {{2}}), ...
                            'test', struct('session', 1, 'runid', {{3:5}}, 'nblocks', {{[1 2 2]}}), ...
                            'VE', struct('session', 1, 'runid', {{6:7}}), ...
                            'adapt', struct('session', 1, 'runid', {{8}}), ...
                            'pretest', struct('session', 2:5, 'runid', {{1 1 1 1}}, ...
                                              'match', {{'L' 'R' 'L' 'R'}}), ...
                            'posttest', struct('session', 2:5,...
                                               'radapt', struct('session', [3 5], ...
                                                                'runid', {{2:3 2:3}}, ...
                                                                'nblocks', {{[5 5] [5 5]}}), ...
                                               'ladapt', struct('session', [2 4], ...
                                                                'runid', {{2:3 2:3}}, ...
                                                                'nblocks', {{[5 5] [5 5]}}))), ...
    'anat', struct('session', 7), ...
    'fMRI', struct('session', 6:9, ...
                   'pretest', struct('session', 6:9, 'runid', {{6:10 5:9 [5:8 10]  [3 5 6:8]}}, ...
                                     'hand', {{['L' 'R' 'L' 'R' 'L'], ['R' 'L' 'R' 'L' 'R'], ...
                                               ['L' 'R' 'L' 'R' 'L'], ['R' 'L' 'R' 'L' 'R']}}, ...
                                     'match', {{'L' 'R' 'R' 'L'}}), ...
                   'posttest', struct('session', 6:9, ...
                                      'radapt', struct('session', 7:8, 'runid', {{11:14 11:15}}, ...
                                                       'hand', {{['L' 'R' 'L' 'R'], ...
                                                                 ['R' 'L' 'R' 'R' 'L']}}, ...
                                                       'min3', {{[1 0 0 0 1 0 0 0] [1 0 1 0 1 1 1 0]}}, ...
                                                       'mergerun', {{[] [4]}}), ...
                                      'ladapt', struct('session', [6 9], 'runid', {{14:19 9:12}}, ...
                                                       'hand', {{['R' 'R' 'L' 'L' 'R' 'L'], ...
                                                                 ['L' 'R' 'L' 'R']}}, ...
                                                       'min3', {{[0 1 1 1 1 0 0 0] ones(1,8)}}, ...
                                                       'mergerun', {{[2 4] []}})), ...
                   'extravol', struct('session', 7, 'runid', {{5}}, 'delete', {{11}})),...
    'EEG', struct('session',10:13, ...
                   'pretest',struct('session',10:13,'runid',{{3:7,2:6,2:6,2:6}},'match',{{'R','L','L','R'}}), ...
                   'posttest',struct('session',10:13, ...
                                     'radapt',struct('session',[10,13], ...
                                                     'runid',{{8:11,7:10}}, ...
                                                     'min3',{{ones(1,16),ones(1,16)}}),...
                                     'ladapt',struct('session',[11,12], ...
                                                     'runid',{{7:10,7:10}}, ...
                                                     'min3',{{ones(1,16),ones(1,16)}})), ...
                   'filespec',struct('session',{10,11,12,13}, ...
                                     'file',{struct('name',{'336_session10_1','336_session10_2'}, ...
                                                  'session',{10,10}, ...
                                                  'nRunsInFile',{5,4}, ...
                                                  'nBlocksInFile',{10,16},...
                                                  'runid',{3:7,8:11},...
                                                  'hand',{{'L','R','L','R','L'},...
                                                          {'R','L','R','L'}},...
                                                  'runsToExclude',{NaN,NaN}, ...
                                                  'blocksToExclude',{NaN,NaN},...
                                                  'cutoff_zval',{4,4}),...
                                            struct('name',{'336_session11_1','336_session11_2'}, ...
                                                  'session',{11,11}, ...
                                                  'nRunsInFile',{5,4}, ...
                                                  'nBlocksInFile',{10,16},...
                                                  'runid',{2:6,7:10},...
                                                  'hand',{{'R','L','R','L','R'},...
                                                          {'L','R','L','R'}},...
                                                  'runsToExclude',{NaN,NaN}, ...
                                                  'blocksToExclude',{NaN,NaN},...
                                                  'cutoff_zval',{4,4}),...
                                            struct('name',{'336_session12_1','336_session12_2'}, ...
                                                  'session',{12,12}, ...
                                                  'nRunsInFile',{5,4}, ...
                                                  'nBlocksInFile',{10,16},...
                                                  'runid',{2:6,7:10},...
                                                  'hand',{{'L','R','L','R','L'},...
                                                          {'R','L','R','L'}},...
                                                  'runsToExclude',{NaN,NaN}, ...
                                                  'blocksToExclude',{NaN,NaN},...
                                                  'cutoff_zval',{4,4}),...
                                            struct('name',{'336_session13_1','336_session13_2'}, ...
                                                  'session',{13,13}, ...
                                                  'nRunsInFile',{5,4}, ...
                                                  'nBlocksInFile',{10,16},...
                                                  'runid',{2:6,7:10},...
                                                  'hand',{{'R','L','R','L','R'},...
                                                          {'L','R','L','R'}},...
                                                  'runsToExclude',{NaN,NaN}, ...
                                                  'blocksToExclude',{NaN,NaN},...
                                                  'cutoff_zval',{4,4})})));
            
subjects(3) = struct('id', '340', ...
    'session_folder_name',{{'2016_12_08','2016_12_09','2017_01_14','2017_01_15','2017_01_17', ...
                            '2017_01_28','2017_01_29','2017_02_04','2017_02_05','2017_05_11','2017_05_12',...
                            '2017_05_13','2017_05_14'}}, ...
    'psychophysics', struct('baseline', struct('session', 1, 'runid', {{2}}), ...
                            'test', struct('session', 1, 'runid', {{3:5}}, 'nblocks', {{[1 2 2]}}), ...
                            'VE', struct('session', 1, 'runid', {{6:7}}), ...
                            'adapt', struct('session', 1, 'runid', {{8}}), ...
                            'pretest', struct('session', 2:5, 'runid', {{1 1 1 1}}, 'match', {{'R' 'R' 'L' 'L'}}), ...
                            'posttest', struct('session', 2:5,...
                                               'radapt', struct('session', 2:3, ...
                                                                'runid', {{2:3 2:3}}, ...
                                                                'nblocks', {{[5 5] [5 5]}}), ...
                                               'ladapt', struct('session', 4:5, ...
                                                                'runid', {{2:3 2:3}}, ...
                                                                'nblocks', {{[5 5] [5 5]}}))), ...
    'anat', struct('session', 8), ...
    'fMRI', struct('session', 6:9, ...
                   'pretest', struct('session', 6:9, 'runid', {{4:8 4:8 4:8 2:6}}, ...
                                     'hand', {{['L' 'R' 'L' 'R' 'L'], ['R' 'L' 'R' 'L' 'R'], ...
                                               ['L' 'R' 'L' 'R' 'L'], ['R' 'L' 'R' 'L' 'R']}}, ...
                                     'match', {{'L' 'R' 'R' 'L'}}), ...
                   'posttest', struct('session', 6:9, ...
                                      'radapt', struct('session', 7:8, 'runid', {{9:12 9:12}}, ...
                                                       'hand', {{['L' 'R' 'L' 'R'], ...
                                                                 ['R' 'L' 'R' 'L']}}, ...
                                                       'min3', {{ones(1, 8) ones(1, 8)}}, ...
                                                       'mergerun', {{[] []}}), ...
                                      'ladapt', struct('session', [6 9], 'runid', {{9:12 7:10}}, ...
                                                       'hand', {{['R' 'L' 'R' 'L'], ...
                                                                 ['L' 'R' 'L' 'R']}}, ...
                                                       'min3', {{ones(1, 8) ones(1, 8)}}, ...
                                                       'mergerun', {{[] []}}))),...
    'EEG', struct('session',10:13, ...
                   'pretest',struct('session',10:13,'runid',{{4:8,2:6,2:6,2:6}},'match',{{'R','L','L','R'}}), ...
                   'posttest',struct('session',10:13, ...
                                     'radapt',struct('session',[10,13], ...
                                                     'runid',{{9:12,7:10}}, ...
                                                     'min3',{{ones(1,16),ones(1,16)}}),...
                                     'ladapt',struct('session',[11,12], ...
                                                     'runid',{{7:10,7:10}}, ...
                                                     'min3',{{ones(1,16),ones(1,16)}})), ...
                   'filespec',struct('session',{10,11,12,13}, ...
                                     'file',{struct('name',{'340_session10_1','340_session10_2'}, ...
                                                  'session',{10,10}, ...
                                                  'nRunsInFile',{5,4}, ...
                                                  'nBlocksInFile',{10,16},...
                                                  'runid',{4:8,9:12},...
                                                  'hand',{{'L','R','L','R','L'},...
                                                          {'R','L','R','L'}},...
                                                  'runsToExclude',{NaN,NaN}, ...
                                                  'blocksToExclude',{NaN,NaN},...
                                                  'cutoff_zval',{4,4}),...
                                            struct('name',{'340_session11_1','340_session11_2'}, ...
                                                  'session',{11,11}, ...
                                                  'nRunsInFile',{5,4}, ...
                                                  'nBlocksInFile',{10,16},...
                                                  'runid',{2:6,7:10},...
                                                  'hand',{{'R','L','R','L','R'},...
                                                          {'L','R','L','R'}},...
                                                  'runsToExclude',{NaN,NaN}, ...
                                                  'blocksToExclude',{NaN,NaN},...
                                                  'cutoff_zval',{4,4}),...
                                            struct('name',{'340_session12_1','340_session12_2'}, ...
                                                  'session',{12,12}, ...
                                                  'nRunsInFile',{5,4}, ...
                                                  'nBlocksInFile',{10,16},...
                                                  'runid',{2:6,7:10},...
                                                  'hand',{{'L','R','L','R','L'},...
                                                          {'R','L','R','L'}},...
                                                  'runsToExclude',{NaN,NaN}, ...
                                                  'blocksToExclude',{NaN,NaN},...
                                                  'cutoff_zval',{4,4}),...
                                            struct('name',{'340_session13_1','340_session13_2'}, ...
                                                  'session',{13,13}, ...
                                                  'nRunsInFile',{5,4}, ...
                                                  'nBlocksInFile',{10,16},...
                                                  'runid',{2:6,7:10},...
                                                  'hand',{{'R','L','R','L','R'},...
                                                          {'L','R','L','R'}},...
                                                  'runsToExclude',{NaN,NaN}, ...
                                                  'blocksToExclude',{NaN,NaN},...
                                                  'cutoff_zval',{4,4})})));
        
subjects(4) = struct('id', '345', ...
    'session_folder_name',{{'2016_12_11','2016_12_20','2016_12_21','2017_01_13','2017_01_20', ...
                            '2017_01_28','2017_02_10','2017_02_18','2017_02_19','2017_05_25','2017_05_27',...
                            '2017_05_31','2017_06_04'}}, ...
    'psychophysics', struct('baseline', struct('session', 1, 'runid', {{2}}), ...
                            'test', struct('session', 1, 'runid', {{3:5}}, 'nblocks', {{[1 2 2]}}), ...
                            'VE', struct('session', 1, 'runid', {{6:7}}), ...
                            'adapt', struct('session', 1, 'runid', {{8}}), ...
                            'pretest', struct('session', 2:5, 'runid', {{1 1 1 1}}, 'match', {{'R' 'R' 'L' 'L'}}), ...
                            'posttest', struct('session', 2:5,...
                                               'radapt', struct('session', 2:3, ...
                                                                'runid', {{2:3 2:3}}, ...
                                                                'nblocks', {{[5 5] [5 5]}}), ...
                                               'ladapt', struct('session', 4:5, ...
                                                                'runid', {{2:3 2:3}}, ...
                                                                'nblocks', {{[5 5] [5 5]}}))), ...
    'anat', struct('session', 6), ...   
    'fMRI', struct('session', 6:9, ...
                   'pretest', struct('session', 6:9, 'runid', {{7:11 2:6 4:8 5:9}}, ...
                                     'hand', {{['R' 'L' 'R' 'L' 'R'], ['L' 'R' 'L' 'R' 'L'], ...
                                               ['R' 'L' 'R' 'L' 'R'], ['L' 'R' 'L' 'R' 'L']}}, ...
                                     'match', {{'R' 'L' 'L' 'R'}}), ...
                   'posttest', struct('session', 6:9, ...
                                      'radapt', struct('session', [6 9], 'runid', {{12:15 [10:11 13:14]}}, ...
                                                       'hand', {{['L' 'R' 'L' 'R'], ...
                                                                 ['R' 'L' 'R' 'L']}}, ...
                                                       'min3', {{ones(1, 8) ones(1, 8)}}, ...
                                                       'mergerun', {{[] []}}), ...
                                      'ladapt', struct('session', 7:8, 'runid', {{7:10 9:12}}, ...
                                                       'hand', {{['R' 'L' 'R' 'L'], ...
                                                                 ['L' 'R' 'L' 'R']}}, ...
                                                       'min3', {{ones(1, 8) ones(1, 8)}}, ...
                                                       'mergerun', {{[] []}}))),...
    'EEG', struct('session',10:13, ...
                   'pretest',struct('session',10:13,'runid',{{4:8,2:6,3:7,5:9}},'match',{{'L','R','R','L'}}), ...
                   'posttest',struct('session',10:13, ...
                                     'radapt',struct('session',[11,12], ...
                                                     'runid',{{7:10,8:11}}, ...
                                                     'min3',{{ones(1,16),ones(1,16)}}),...
                                     'ladapt',struct('session',[10,13], ...
                                                     'runid',{{9:12,10:13}}, ...
                                                     'min3',{{ones(1,16),ones(1,16)}})), ...
                   'filespec',struct('session',{10,11,12,13}, ...
                                     'file',{struct('name',{'345_session10_1','345_session10_2'}, ...
                                                  'session',{10,10}, ...
                                                  'nRunsInFile',{5,4}, ...
                                                  'nBlocksInFile',{10,16},...
                                                  'runid',{4:8,9:12},...
                                                  'hand',{{'L','R','L','R','L'},...
                                                          {'R','L','R','L'}},...
                                                  'runsToExclude',{NaN,NaN}, ...
                                                  'blocksToExclude',{NaN,NaN},...
                                                  'cutoff_zval',{4,4}),...
                                            struct('name',{'345_session11_1','345_session11_2'}, ...
                                                  'session',{11,11}, ...
                                                  'nRunsInFile',{5,4}, ...
                                                  'nBlocksInFile',{10,16},...
                                                  'runid',{2:6,7:10},...
                                                  'hand',{{'R','L','R','L','R'},...
                                                          {'L','R','L','R'}},...
                                                  'runsToExclude',{NaN,NaN}, ...
                                                  'blocksToExclude',{NaN,NaN},...
                                                  'cutoff_zval',{4,4}),...
                                            struct('name',{'345_session12_1','345_session12_2'}, ...
                                                  'session',{12,12}, ...
                                                  'nRunsInFile',{5,4}, ...
                                                  'nBlocksInFile',{10,16},...
                                                  'runid',{3:7,8:11},...
                                                  'hand',{{'L','R','L','R','L'},...
                                                          {'R','L','R','L'}},...
                                                  'runsToExclude',{NaN,NaN}, ...
                                                  'blocksToExclude',{NaN,NaN},...
                                                  'cutoff_zval',{4,4}),...
                                            struct('name',{'345_session13_1','345_session13_2'}, ...
                                                  'session',{13,13}, ...
                                                  'nRunsInFile',{6,4}, ...
                                                  'nBlocksInFile',{12,16},...
                                                  'runid',{5:9,10:13},...
                                                  'hand',{{'R','L','R','L','R'},...
                                                          {'L','R','L','R'}},...
                                                  'runsToExclude',{1,NaN}, ...
                                                  'blocksToExclude',{1:2,NaN},...
                                                  'cutoff_zval',{4,4})})));
     
subjects(5) = struct('id', '346', ...
    'session_folder_name',{{'2017_01_09','2017_01_14','2017_01_15','2017_01_16','2017_01_17', ...
                            '2017_01_28','2017_01_29','2017_02_11','2017_02_13','2017_05_20',...
                            '2017_05_21','2017_05_26','2017_06_02'}}, ...
    'psychophysics', struct('baseline', struct('session', 1, 'runid', {{2}}), ...
                            'test', struct('session', 1, 'runid', {{4:6}}, 'nblocks', {{[1 2 2]}}), ...
                            'VE', struct('session', 1, 'runid', {{7:8}}), ...
                            'adapt', struct('session', 1, 'runid', {{9}}), ...
                            'pretest', struct('session', 2:5, 'runid', {{1 1:2 1 1}}, ...
                                              'match', {{'L' 'L' 'R' 'R'}}), ...
                            'posttest', struct('session', 2:5,...
                                               'radapt', struct('session', 4:5, ...
                                                                'runid', {{2:3 2:3}}, ...
                                                                'nblocks', {{[5 5] [5 5]}}), ...
                                               'ladapt', struct('session', 2:3, ...
                                                                'runid', {{2:3 3:4}}, ...
                                                                'nblocks', {{[5 5] [5 5]}}))), ...
    'anat', struct('session', 7), ...
    'fMRI', struct('session', 6:9, ...
                   'pretest', struct('session', 6:9, 'runid', {{8:12 4:8 5:9 2:6}}, ...
                                     'hand', {{['R' 'L' 'R' 'L' 'R'], ['L' 'R' 'L' 'R' 'L'], ...
                                               ['R' 'L' 'R' 'L' 'R'], ['L' 'R' 'L' 'R' 'L']}}, ...
                                     'match', {{'L' 'R' 'R' 'L'}}), ...
                   'posttest', struct('session', 6:9, ...
                                      'radapt', struct('session', 7:8, 'runid', {{10:13 10:13}}, ...
                                                       'hand', {{['R' 'L' 'R' 'L'], ...
                                                                 ['L' 'R' 'L' 'R']}}, ...
                                                       'min3', {{ones(1, 8) ones(1, 8)}}, ...
                                                       'mergerun', {{[] []}}), ...
                                      'ladapt', struct('session', [6 9], 'runid', {{13:16 7:10}}, ...
                                                       'hand', {{['L' 'R' 'L' 'R'], ...
                                                                 ['R' 'L' 'R' 'L']}}, ...
                                                       'min3', {{ones(1, 8) ones(1, 8)}}, ...
                                                       'mergerun', {{[] []}}))),...
    'EEG', struct('session',10:13, ...
                   'pretest',struct('session',10:13,'runid',{{2:6,2:6,2:6,3:7}},'match',{{'R','L','L','R'}}), ...
                   'posttest',struct('session',10:13, ...
                                     'radapt',struct('session',[10,13], ...
                                                     'runid',{{7:10,8:11}}, ...
                                                     'min3',{{ones(1,16),ones(1,16)}}),...
                                     'ladapt',struct('session',[11,12], ...
                                                     'runid',{{7:10,7:10}}, ...
                                                     'min3',{{ones(1,16),ones(1,16)}})), ...
                   'filespec',struct('session',{10,11,12,13}, ...
                                     'file',{struct('name',{'346_session10_1','346_session10_2'}, ...
                                                  'session',{10,10}, ...
                                                  'nRunsInFile',{6,4}, ...
                                                  'nBlocksInFile',{10,16},...
                                                  'runid',{2:6,7:10},...
                                                  'hand',{{'R','L','R','L','R'},...
                                                          {'L','R','L','R'}},...
                                                  'runsToExclude',{1,NaN}, ...
                                                  'blocksToExclude',{NaN,NaN},...
                                                  'cutoff_zval',{4,4}),...
                                            struct('name',{'346_session11_1','346_session11_2'}, ...
                                                  'session',{11,11}, ...
                                                  'nRunsInFile',{5,4}, ...
                                                  'nBlocksInFile',{10,16},...
                                                  'runid',{2:6,7:10},...
                                                  'hand',{{'L','R','L','R','L'},...
                                                          {'R','L','R','L'}},...
                                                  'runsToExclude',{NaN,NaN}, ...
                                                  'blocksToExclude',{NaN,NaN},...
                                                  'cutoff_zval',{4,4}),...
                                            struct('name',{'346_session12_1','346_session12_2'}, ...
                                                  'session',{12,12}, ...
                                                  'nRunsInFile',{8,4}, ...
                                                  'nBlocksInFile',{13,16},...
                                                  'runid',{2:6,7:10},...
                                                  'hand',{{'R','L','R','L','R'},...
                                                          {'L','R','L','R'}},...
                                                  'runsToExclude',{1:3,NaN}, ...
                                                  'blocksToExclude',{1:3,NaN},...
                                                  'cutoff_zval',{4,4}),...
                                            struct('name',{'346_session13_1','346_session13_2'}, ...
                                                  'session',{13,13}, ...
                                                  'nRunsInFile',{5,4}, ...
                                                  'nBlocksInFile',{10,16},...
                                                  'runid',{3:7,8:11},...
                                                  'hand',{{'L','R','L','R','L'},...
                                                          {'R','L','R','L'}},...
                                                  'runsToExclude',{NaN,NaN}, ...
                                                  'blocksToExclude',{NaN,NaN},...
                                                  'cutoff_zval',{4,4})})));
        
%% Behavioural-only subjects

subjects(6) = struct('id', '334',...
    'session_folder_name',{{}}, ...
    'psychophysics', struct(...
        'baseline', struct('session', 1, 'runid', {{2}}), ...
        'test', struct('session', 1, 'runid', {{3:5}}, 'nblocks', {{[1 2 2]}}), ...
        'VE', struct('session', 1, 'runid', {{6:8}}), ...
        'adapt', struct('session', 1, 'runid', {{10}}), ...
        'pretest', struct('session', 2:5, 'runid', {{1 1 1 1}}, 'match', {{'L' 'R' 'L' 'R'}}), ...
        'posttest', struct('session', 2:5,...
            'radapt', struct('session', [3 5], 'runid', {{2:3 2:3}}, 'nblocks', {{[5 3] [5 5]}}), ...
            'ladapt', struct('session', [2 4], 'runid', {{2:3 2:3}}, 'nblocks', {{[5 5] [5 5]}}))), ...
    'anat', struct(), ...
    'fMRI', struct(), ...
    'EEG', struct());

subjects(7) = struct('id', '335',...
    'session_folder_name',{{}}, ...
    'psychophysics', struct(...
        'baseline', struct('session', 1, 'runid', {{2}}), ...
        'test', struct('session', 1, 'runid', {{3:5}}, 'nblocks', {{[1 2 2]}}), ...
        'VE', struct('session', 1, 'runid', {{6:7}}), ...
        'adapt', struct('session', 1, 'runid', {{8}}), ...
        'pretest', struct('session', 2:5, 'runid', {{1 1 1 1}}, 'match', {{'R' 'L' 'R' 'L'}}), ...
        'posttest', struct('session', 2:5,...
            'radapt', struct('session', [2 4], 'runid', {{2:3 2:3}}, 'nblocks', {{[5 5] [5 5]}}), ...
            'ladapt', struct('session', [3 5], 'runid', {{2:3 2:3}}, 'nblocks', {{[5 5] [5 5]}}))), ...
    'anat', struct(), ...
    'fMRI', struct(), ...
    'EEG', struct());
        
subjects(8) = struct('id', '315', ...
    'session_folder_name',{{}}, ...
    'psychophysics', struct(...
        'baseline', struct('session', 1, 'runid', {{2}}), ...
        'test', struct('session', 1, 'runid', {{3:5}}, 'nblocks', {{[1 2 2]}}), ...
        'VE', struct('session', 1, 'runid', {{6:7}}), ...
        'adapt', struct('session', 1, 'runid', {{}}), ...
        'pretest', struct('session', 2:5, 'runid', {{1 1 1 1}}, 'match', {{'R' 'L' 'R' 'L'}}), ...
        'posttest', struct('session', 2:5,...
            'radapt', struct('session', [2 4], 'runid', {{2:3 2:3}}, 'nblocks', {{[5 5] [5 5]}}), ...
            'ladapt', struct('session', [3 5], 'runid', {{2:3 2:3}}, 'nblocks', {{[5 5] [5 5]}}))), ...
    'anat', struct(), ...
    'fMRI', struct(), ...
    'EEG', struct());

subjects(9) = struct('id', '337', ...
    'session_folder_name',{{}}, ...
    'psychophysics', struct(...
        'baseline', struct('session', 1, 'runid', {{2}}), ...
        'test', struct('session', 1, 'runid', {{3:5}}, 'nblocks', {{[1 2 2]}}), ...
        'VE', struct('session', 1, 'runid', {{6:7}}), ...
        'adapt', struct('session', 1, 'runid', {{8:10}}), ...
        'pretest', struct('session', 2:5, 'runid', {{1 1 1 1}}, 'match', {{'R' 'L' 'R' 'L'}}), ...
        'posttest', struct('session', 2:5,...
            'radapt', struct('session', [2 4], 'runid', {{2:3 2:3}}, 'nblocks', {{[5 5] [5 5]}}), ...
            'ladapt', struct('session', [3 5], 'runid', {{2:3 2:3}}, 'nblocks', {{[5 5] [5 5]}}))), ...
    'anat', struct(), ...
    'fMRI', struct(), ...
    'EEG', struct());

subjects(10) = struct('id', '338', ...
    'session_folder_name',{{}}, ...
    'psychophysics', struct(...
        'baseline', struct('session', 1, 'runid', {{2}}), ...
        'test', struct('session', 1, 'runid', {{3:5}}, 'nblocks', {{[1 2 2]}}), ...
        'VE', struct('session', 1, 'runid', {{6:7}}), ...
        'adapt', struct('session', 1, 'runid', {{9}}), ...
        'pretest', struct('session', 2:5, 'runid', {{1 1 1 1}}, 'match', {{'L' 'R' 'L' 'R'}}), ...
        'posttest', struct('session', 2:5,...
            'radapt', struct('session', [3 5], 'runid', {{2:3 2:3}}, 'nblocks', {{[5 5] [5 5]}}), ...
            'ladapt', struct('session', [2 4], 'runid', {{2:3 2:3}}, 'nblocks', {{[5 5] [5 5]}}))), ...
    'anat', struct(), ...
    'fMRI', struct(), ...
    'EEG', struct());
    
subjects(11) = struct('id', '341', ...
    'session_folder_name',{{}}, ...
    'psychophysics', struct(...
        'baseline', struct('session', 1, 'runid', {{2}}), ...
        'test', struct('session', 1, 'runid', {{4:6}}, 'nblocks', {{[1 2 2]}}), ...
        'VE', struct('session', 1, 'runid', {{7:8}}), ...
        'adapt', struct('session', 1, 'runid', {{9}}), ...
        'pretest', struct('session', 2:5, 'runid', {{1 1 1 1}}, 'match', {{'L' 'L' 'R' 'R'}}), ...
        'posttest', struct('session', 2:5,...
            'radapt', struct('session', 4:5, 'runid', {{2:3 2:3}}, 'nblocks', {{[5 5] [5 5]}}), ...
            'ladapt', struct('session', 2:3, 'runid', {{2:3 2:3}}, 'nblocks', {{[5 5] [5 5]}}))), ...
    'anat', struct(), ...
    'fMRI', struct(), ...
    'EEG', struct());

subjects(12) = struct('id', '343', ...
    'session_folder_name',{{}}, ...
    'psychophysics', struct(...
        'baseline', struct('session', 1, 'runid', {{2}}), ...
        'test', struct('session', 1, 'runid', {{4:6}}, 'nblocks', {{[1 2 2]}}), ...
        'VE', struct('session', 1, 'runid', {{7:8}}), ...
        'adapt', struct('session', 1, 'runid', {{9}}), ...
        'pretest', struct('session', 2:5, 'runid', {{1 1 1 1}}, 'match', {{'L' 'R' 'R' 'L'}}), ...
        'posttest', struct('session', 2:5,...
            'radapt', struct('session', [3 4], 'runid', {{2:3 2:4}}, 'nblocks', {{[5 5] [5 1 4]}}), ...
            'ladapt', struct('session', [2 5], 'runid', {{2:3 2:3}}, 'nblocks', {{[5 5] [5 5]}}))), ...
    'anat', struct(), ...
    'fMRI', struct(), ...
    'EEG', struct());
    
subjects(13) = struct('id', '344', ...
    'session_folder_name',{{}}, ...
    'psychophysics', struct(...
        'baseline', struct('session', 1, 'runid', {{2}}), ...
        'test', struct('session', 1, 'runid', {{3:5}}, 'nblocks', {{[1 2 2]}}), ...
        'VE', struct('session', 1, 'runid', {{6:7}}), ...
        'adapt', struct('session', 1, 'runid', {{8}}), ...
        'pretest', struct('session', 2:5, 'runid', {{1 1 1 1}}, 'match', {{'R' 'L' 'L' 'R'}}), ...
        'posttest', struct('session', 2:5,...
            'radapt', struct('session', [2 5], 'runid', {{2:3 2:3}}, 'nblocks', {{[5 5] [5 5]}}), ...
            'ladapt', struct('session', [3 4], 'runid', {{2:3 2:3}}, 'nblocks', {{[5 5] [5 5]}}))), ...
    'anat', struct(), ...
    'fMRI', struct(), ...
    'EEG', struct());
            
subjects(14) = struct('id', '350', ...
    'session_folder_name',{{}}, ...
    'psychophysics', struct(...
        'baseline', struct('session', 1, 'runid', {{2}}), ...
        'test', struct('session', 1, 'runid', {{3:5}}, 'nblocks', {{[1 2 2]}}), ...
        'VE', struct('session', 1, 'runid', {{6:8}}), ...
        'adapt', struct('session', 1, 'runid', {{9}}), ...
        'pretest', struct('session', 2:5, 'runid', {{1 1 1 1}}, 'match', {{'R' 'L' 'L' 'R'}}), ...
        'posttest', struct('session', 2:5,...
            'radapt', struct('session', [2 5], 'runid', {{2:3 2:3}}, 'nblocks', {{[5 5] [5 5]}}), ...
            'ladapt', struct('session', 3:4, 'runid', {{2:3 2:3}}, 'nblocks', {{[5 5] [5 5]}}))), ...
    'anat', struct(), ...
    'fMRI', struct(), ...
    'EEG', struct());

subjects(15) = struct('id', '348', ...
    'session_folder_name',{{}}, ...
    'psychophysics', struct(...
        'baseline', struct('session', 1, 'runid', {{2}}), ...
        'test', struct('session', 1, 'runid', {{4:6}}, 'nblocks', {{[1 2 2]}}), ...
        'VE', struct('session', 1, 'runid', {{7:9}}), ...
        'adapt', struct('session', 1, 'runid', {{10}}), ...
        'pretest', struct('session', 2:5, 'runid', {{1 1 1 1:2}}, 'match', {{'L' 'R' 'R' 'L'}}), ...
        'posttest', struct('session', 2:5,...
            'radapt', struct('session', 3:4, 'runid', {{2:3 2:3}}, 'nblocks', {{[5 5] [5 5]}}), ...
            'ladapt', struct('session', [2 5], 'runid', {{2:3 3:4}}, 'nblocks', {{[5 5] [1 5]}}))), ...
    'anat', struct(), ...
    'fMRI', struct(), ...
    'EEG', struct());